---
- name: Disable IPv6 on Windows
  hosts: all
  tasks:
    - name: Disable IPv6 via registry
      ansible.windows.win_shell: |
        New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters" -Name "DisabledComponents" -Value 0xff -PropertyType DWord -Force
