---
- name: Disable IPv6 on Windows Hosts
  hosts: windows
  tasks:
    - name: Disable IPv6
      win_regedit:
        path: HKLM\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters
        name: DisabledComponents
        data: 0xFF
        type: dword
      become: yes
