##CID-##:Ensure IPv6 is disabled on windows"
---
- name: Disable IPv6 on Windows Hosts
  hosts: all
  gather_facts: no
  tasks:
    - name: Disable IPv6
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters
        name: DisabledComponents
        data: 0xff
        type: dword


##CID-##:Ensure to disable SMBv1"
       
- name: Disable SMBv1 via registry (all Windows versions)
  hosts: all
      ansible.windows.win_regedit:path: HKLM:\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters
        name: SMB1
        data: 0type: dword
      ignore_errors: yes

      
##CID-##:Ensure to disable SMBv1 to client"

    - name: Disable SMBv1 client via registry
      hosts: all
      ansible.windows.win_regedit:path: HKLM:\SYSTEM\CurrentControlSet\Services\mrxsmb10
        name: Start
        data: 4type: dword
      ignore_errors: yes
