##CID-##:Ensure IPv6 is disabled on windows"
---
- name: Disable IPv6 on Windows Hosts
  hosts: all
  gather_facts: no
  tasks:
    - name: Disable IPv6
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters
        name: DisabledComponents
        data: 0xff
        type: dword


##CID-##:Ensure to disable SMBv1"
       
- name: Disable SMBv1 via registry (all Windows versions)
  hosts: all
  gather_facts: no
  tasks:
    - name: Disable SMBv1
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters
        name: SMB1
        data: 0
        type: dword
        
  ##CID-5266:Allow Local System to use computer identity for NTLM

- name: Allow Local System to use computer identity for NTLM
  hosts: all
  gather_facts: no
  tasks:
    - name: UseMachineId
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa
        name: UseMachineId
        data: 1
        type: dword
        state: present
      

